import type { IPost } from '../../types/interfaces';

export const POSTS: IPost[] = [
  {
    _id: '1',
    text: "Let's build a fullstack WhatsApp clone with NEXT.JS 14 😍",
    image: '/posts/post1.png',
    user: {
      _id: '123',
      userName: 'johndoe',
      profileImage: '/avatars/boy1.png',
      fullName: 'John Doe',
    },
    comments: [
      {
        _id: '1',
        text: 'Nice Tutorial',
        user: {
          _id: '123',
          userName: 'janedoe',
          profileImage: '/avatars/girl1.png',
          fullName: 'Jane Doe',
        },
      },
    ],
    likes: ['6658s891', '6658s892', '6658s893', '6658s894'],
  },
  {
    _id: '2',
    text: 'How you guys doing? 😊',
    user: {
      _id: '1233',

      userName: 'johndoe',
      profileImage: '/avatars/boy2.png',
      fullName: 'John Doe',
    },
    comments: [
      {
        _id: '1',
        text: 'Nice Tutorial',
        user: {
          _id: '1235',

          userName: 'janedoe',
          profileImage: '/avatars/girl2.png',
          fullName: 'Jane Doe',
        },
      },
    ],
    likes: ['6658s891', '6658s892', '6658s893', '6658s894'],
  },
  {
    _id: '3',
    text: 'Astronaut in a room of drawers, generated by Midjourney. 🚀',
    image: '/posts/post2.png',
    user: {
      _id: '1263',

      userName: 'johndoe',
      profileImage: '/avatars/boy3.png',
      fullName: 'John Doe',
    },
    comments: [],
    likes: [
      '6658s891',
      '6658s892',
      '6658s893',
      '6658s894',
      '6658s895',
      '6658s896',
    ],
  },
  {
    _id: '4',
    text: "I'm learning GO this week. Any tips? 🤔",
    image: '/posts/post3.png',
    user: {
      _id: '1421',
      userName: 'johndoe',
      profileImage: '/avatars/boy3.png',
      fullName: 'John Doe',
    },
    comments: [
      {
        _id: '1',
        text: 'Nice Tutorial',
        user: {
          _id: '52151',
          userName: 'janedoe',
          profileImage: '/avatars/girl3.png',
          fullName: 'Jane Doe',
        },
      },
    ],
    likes: [
      '6658s891',
      '6658s892',
      '6658s893',
      '6658s894',
      '6658s895',
      '6658s896',
      '6658s897',
      '6658s898',
      '6658s899',
    ],
  },
];

export const USERS_FOR_RIGHT_PANEL = [
  {
    _id: '1',
    fullName: 'John Doe',
    userName: 'johndoe',
    profileImage: '/avatars/boy2.png',
  },
  {
    _id: '2',
    fullName: 'Jane Doe',
    userName: 'janedoe',
    profileImage: '/avatars/girl1.png',
  },
  {
    _id: '3',
    fullName: 'Bob Doe',
    userName: 'bobdoe',
    profileImage: '/avatars/boy3.png',
  },
  {
    _id: '4',
    fullName: 'Daisy Doe',
    userName: 'daisydoe',
    profileImage: '/avatars/girl2.png',
  },
];
